apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-registration-app
  namespace: user-register
  labels:
    app: user-registration-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: user-registration-app
  template:
    metadata:
      labels:
        app: user-registration-app
    spec:
      containers:
      - name: user-registration-app
        image: USER_REGISTRATION_APP_IMAGE
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: host
        - name: DB_NAME
          value: "userdb"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: DB_PORT
          value: "5432"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret-key
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 5