apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-registration-app
  labels:
    app: user-registration-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-registration-app
  template:
    metadata:
      labels:
        app: user-registration-app
    spec:
      containers:
      - name: user-registration-app
        image: USER_REGISTRATION_APP_IMAGE
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: user-registration-app-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: user-registration-app-config
              key: DB_PORT
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  host: # Will be filled during deployment
  username: # Will be filled during deployment  
  password: # Will be filled during deployment
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  secret-key: # Will be filled during deployment