name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - staging
      confirm_destroy:
        description: 'Type "DESTROY" to confirm destruction'
        required: true
        type: string

env:
  AWS_REGION: us-west-2
  PROJECT_NAME: user-registration

jobs:
  validate-destroy:
    runs-on: ubuntu-latest
    outputs:
      should_destroy: ${{ steps.confirm.outputs.should_destroy }}
      environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Confirm destruction
      id: confirm
      run: |
        if [ "${{ github.event.inputs.confirm_destroy }}" = "DESTROY" ]; then
          echo "✅ Destruction confirmed for environment: ${{ github.event.inputs.environment }}"
          echo "should_destroy=true" >> $GITHUB_OUTPUT
        else
          echo "❌ Destruction not confirmed. Please type 'DESTROY' to confirm."
          echo "should_destroy=false" >> $GITHUB_OUTPUT
          exit 1
        fi

  destroy-infrastructure:
    needs: validate-destroy
    if: needs.validate-destroy.outputs.should_destroy == 'true'
    runs-on: ubuntu-latest
    environment: ${{ needs.validate-destroy.outputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Destroy
      run: |
        cd terraform
        echo "Destroying infrastructure for environment: ${{ needs.validate-destroy.outputs.environment }}"
        terraform destroy \
          -var="environment=${{ needs.validate-destroy.outputs.environment }}" \
          -var="project_name=${{ env.PROJECT_NAME }}" \
          -auto-approve

    - name: Cleanup ECR Repository
      run: |
        # Delete ECR repository
        aws ecr delete-repository \
          --repository-name ${{ env.PROJECT_NAME }}-app \
          --region ${{ env.AWS_REGION }} \
          --force \
          --output text || true
        echo "✅ ECR repository deleted"

    - name: Destruction Summary
      run: |
        echo ""
        echo "🗑️ DESTRUCTION SUMMARY"
        echo "===================="
        echo "Environment: ${{ needs.validate-destroy.outputs.environment }}"
        echo "Destroyed by: ${{ github.actor }}"
        echo "Destruction Time: $(date)"
        echo "✅ All resources have been destroyed"
        echo ""